### ISSUE TITLE
Initialization error in PubsubLiteSinkConnector

### ISSUE THREAD

**Issue by samarthsingal** [googleapis/java-pubsub-group-kafka-connector#98]
Bug was introduced in https://github.com/googleapis/java-pubsub-group-kafka-connector/pull/83. In PublisherFactoryImpl.java, [`getPartitionPublisherFactory` does not set value for required property `streamFactory`](https://github.com/googleapis/java-pubsub-group-kafka-connector/blob/243df288405327e2468fd8ad6220daa173599149/src/main/java/com/google/pubsublite/kafka/sink/PublisherFactoryImpl.java#L41-L47) causing Autovalue validation to fail on reflection and an uncaught exception to be raised. The ultimate result is that the `PubsubLiteSinkTask` is never properly initialized.

#### Steps to reproduce
1. Try to bring up a PubsubLiteSinkConnector.java task

#### Stack trace
```
1768-[2022-09-07 17:46:32,076] ERROR [PubSubLiteSinkConnector|task-0] WorkerSinkTask{id=PubSubLiteSinkConnector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:195)
1769:java.lang.IllegalStateException: Missing required properties: streamFactory
1770-   at com.google.cloud.pubsublite.internal.wire.AutoValue_SinglePartitionPublisherBuilder$Builder.autoBuild(AutoValue_SinglePartitionPublisherBuilder.java:173)
1771-   at com.google.cloud.pubsublite.internal.wire.SinglePartitionPublisherBuilder$Builder.build(SinglePartitionPublisherBuilder.java:67)
1772-   at com.google.pubsublite.kafka.sink.PublisherFactoryImpl$1.newPublisher(PublisherFactoryImpl.java:47)
1773-   at com.google.cloud.pubsublite.internal.wire.RoutingPublisherBuilder$Builder.build(RoutingPublisherBuilder.java:69)
1774-   at com.google.pubsublite.kafka.sink.PublisherFactoryImpl.newPublisher(PublisherFactoryImpl.java:69)
1775-   at com.google.pubsublite.kafka.sink.PubSubLiteSinkTask.start(PubSubLiteSinkTask.java:64)
1776-   at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:312)
1777-   at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:186)
1778-   at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
1779-   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
1780-   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
1781-   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
1782-   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
1783-   at java.base/java.lang.Thread.run(Thread.java:829)
1784-[2022-09-07 17:46:32,079] WARN [PubSubLiteSinkConnector|task-0] Could not stop task (org.apache.kafka.connect.runtime.WorkerSinkTask:173)
1785-java.lang.IllegalStateException: Called stop when publisher doesn't exist.
1786-   at com.google.pubsublite.kafka.sink.PubSubLiteSinkTask.stop(PubSubLiteSinkTask.java:138)
1787-   at org.apache.kafka.connect.runtime.WorkerSinkTask.close(WorkerSinkTask.java:171)
1788-   at org.apache.kafka.connect.runtime.WorkerTask.doClose(WorkerTask.java:167)
1789-   at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:199)
1790-   at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
1791-   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
1792-   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
1793-   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
1794-   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
1795-   at java.base/java.lang.Thread.run(Thread.java:829)
1796-[2022-09-07 17:46:32,079] ERROR [PubSubLiteSinkConnector|task-1] WorkerSinkTask{id=PubSubLiteSinkConnector-1} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:195)
1797:java.lang.IllegalStateException: Missing required properties: streamFactory
1798-   at com.google.cloud.pubsublite.internal.wire.AutoValue_SinglePartitionPublisherBuilder$Builder.autoBuild(AutoValue_SinglePartitionPublisherBuilder.java:173)
1799-   at com.google.cloud.pubsublite.internal.wire.SinglePartitionPublisherBuilder$Builder.build(SinglePartitionPublisherBuilder.java:67)
1800-   at com.google.pubsublite.kafka.sink.PublisherFactoryImpl$1.newPublisher(PublisherFactoryImpl.java:47)
1801-   at com.google.cloud.pubsublite.internal.wire.RoutingPublisherBuilder$Builder.build(RoutingPublisherBuilder.java:69)
1802-   at com.google.pubsublite.kafka.sink.PublisherFactoryImpl.newPublisher(PublisherFactoryImpl.java:69)
1803-   at com.google.pubsublite.kafka.sink.PubSubLiteSinkTask.start(PubSubLiteSinkTask.java:64)
1804-   at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:312)
1805-   at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:186)
1806-   at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
1807-   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
1808-   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
1809-   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
1810-   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
1811-   at java.base/java.lang.Thread.run(Thread.java:829)
1812-[2022-09-07 17:46:32,080] WARN [PubSubLiteSinkConnector|task-1] Could not stop task (org.apache.kafka.connect.runtime.WorkerSinkTask:173)
1813-java.lang.IllegalStateException: Called stop when publisher doesn't exist.
1814-   at com.google.pubsublite.kafka.sink.PubSubLiteSinkTask.stop(PubSubLiteSinkTask.java:138)
1815-   at org.apache.kafka.connect.runtime.WorkerSinkTask.close(WorkerSinkTask.java:171)
1816-   at org.apache.kafka.connect.runtime.WorkerTask.doClose(WorkerTask.java:167)
1817-   at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:199)
1818-   at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
1819-   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
1820-   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
1821-   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
1822-   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
1823-   at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by samarthsingal** [comment]
Encountered an error once the stream has been instantiated:
```
1768:[2022-09-07 22:45:33,230] ERROR [PubSubLiteSinkConnector|task-0] WorkerSinkTask{id=PubSubLiteSinkConnector-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:195)
1769-java.lang.NoClassDefFoundError: com/google/common/flogger/GoogleLogger
1770-   at com.google.cloud.pubsublite.internal.ProxyService.<clinit>(ProxyService.java:41)
1771-   at com.google.cloud.pubsublite.internal.wire.SinglePartitionPublisherBuilder$Builder.build(SinglePartitionPublisherBuilder.java:75)
1772-   at com.google.pubsublite.kafka.sink.PublisherFactoryImpl$1.newPublisher(PublisherFactoryImpl.java:85)
1773-   at com.google.cloud.pubsublite.internal.wire.RoutingPublisherBuilder$Builder.build(RoutingPublisherBuilder.java:69)
1774-   at com.google.pubsublite.kafka.sink.PublisherFactoryImpl.newPublisher(PublisherFactoryImpl.java:107)
1775-   at com.google.pubsublite.kafka.sink.PubSubLiteSinkTask.start(PubSubLiteSinkTask.java:64)
1776-   at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:312)
1777-   at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:186)
1778-   at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
1779-   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
1780-   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
1781-   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
1782-   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
1783-   at java.base/java.lang.Thread.run(Thread.java:829)
1784-Caused by: java.lang.ClassNotFoundException: com.google.common.flogger.GoogleLogger
1785-   at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
1786-   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
1787-   at org.apache.kafka.connect.runtime.isolation.PluginClassLoader.loadClass(PluginClassLoader.java:103)
1788-   at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
1789-   ... 14 more
1790:[2022-09-07 22:45:33,230] ERROR [PubSubLiteSinkConnector|task-1] WorkerSinkTask{id=PubSubLiteSinkConnector-1} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask:195)
1791-java.lang.NoClassDefFoundError: Could not initialize class com.google.cloud.pubsublite.internal.wire.SinglePartitionPublisher
1792-   at com.google.cloud.pubsublite.internal.wire.SinglePartitionPublisherBuilder$Builder.build(SinglePartitionPublisherBuilder.java:75)
1793-   at com.google.pubsublite.kafka.sink.PublisherFactoryImpl$1.newPublisher(PublisherFactoryImpl.java:85)
1794-   at com.google.cloud.pubsublite.internal.wire.RoutingPublisherBuilder$Builder.build(RoutingPublisherBuilder.java:69)
1795-   at com.google.pubsublite.kafka.sink.PublisherFactoryImpl.newPublisher(PublisherFactoryImpl.java:107)
1796-   at com.google.pubsublite.kafka.sink.PubSubLiteSinkTask.start(PubSubLiteSinkTask.java:64)
1797-   at org.apache.kafka.connect.runtime.WorkerSinkTask.initializeAndStart(WorkerSinkTask.java:312)
1798-   at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:186)
1799-   at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:243)
1800-   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
1801-   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
1802-   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
1803-   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
1804-   at java.base/java.lang.Thread.run(Thread.java:829)
1805-[2022-09-07 22:45:33,244] WARN [PubSubLiteSinkConnector|task-1] Could not stop task (org.apache.kafka.connect.runtime.WorkerSinkTask:173)
1806-java.lang.IllegalStateException: Called stop when publisher doesn't exist.
1807-   at com.google.pubsublite.kafka.sink.PubSubLiteSinkTask.stop(PubSubLiteSinkTask.java:138)
1808-   at org.apache.kafka.connect.runtime.WorkerSinkTask.close(WorkerSinkTask.java:171)
1809-   at org.apache.kafka.connect.runtime.WorkerTask.doClose(WorkerTask.java:167)
1810-   at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:199)
```

**Comment by samarthsingal** [comment]
https://github.com/googleapis/java-pubsub-group-kafka-connector/commit/0656acc18a15783a8fee6126e6df3e8444bc5a78 fixes the issues. One thing that is odd is that for comment#2 i.e. `java.lang.NoClassDefFoundError: com/google/common/flogger/GoogleLogger`, I had to add the snippet to the POM:
```
    <dependency>
      <groupId>com.google.flogger</groupId>
      <artifactId>google-extensions</artifactId>
      <version>0.7.4</version>
    </dependency>
 ```
 Ideally the Pub/Sub Lite client library should be supplying this in its class path.
